### PR TITLE
Adjustments to support VS 2019

### PR DESCRIPTION
**Pull request by NicoB1981**
+ modified vsixmanifest to install on VS 2019 (had to remove nuget https://github.com/axodox/VsixUpdater for that)
+ Updated all NuGet Packages to current versions, so that project would compile (included a number of new packages from dependencies)
+ Changed RegexTesterPackage to derive from AsyncPackage to be compatible with new async loading model (avoids deprecation warning in VS2019).
+ created alternate signing.pfx since I do not have the password to import the pfx file.

### CODE REVIEW

**Comment by sharomank** [comment]
I've tried to update your PR to support VS 2017 and 2019 at the same time, but it difficult.
In few days and I will merge this PR and release new version.
Thanks!

**Comment by sharomank** [comment]
Hi @NicoB1981,

Could you please update master branch and check how I merged your changes?
I've made some small changes and merge it manually.
If it works on your machine as well, we will release new version soon.

Thanks!

**Comment by NicoB1981** [comment]
Hello Roman,

I just tested the new version from the master branch – no problems at all and shows up, working nicely. I see it now only supports VS2019 – I suppose that makes sense, no need to carry around support for older version, when the extension for the older version is perfect already.

Also didn’t have a chance to mention this earlier:

                Thanks for the great extension. It’s a very valuable tool that I use frequently and it saves me a lot of time!

Best regards

Nico

**Comment by sharomank** [comment]
I am glad to hear it.
Now you can download this tool via Marketplace.
Thanks for your contribution!

**Pull request closed without merging**
